<?php

declare(strict_types=1);

return [
    'regimes' => [
        'ENC' => 'ENC',
        'ECC' => 'ECC',
        'ECP' => 'ECP',
        'ECK' => 'ECK',
        'ECBAPT' => 'ECBAPT',
        'ECADV' => 'ECADV',
        'PRIVEE' => 'PRIVÉE',
    ],

    'teaching_types' => [
        'General' => 'Général',
        'Normal' => 'Normal',
        'Technique' => 'Technique',
        'Professionnel' => 'Professionnel',
        'Art_Metiers' => 'Art et Métiers',
    ],

    'steps' => [
        0 => [
            'key' => 'contexte',
            'label' => 'Contexte',
            'title' => 'Identification de la collecte',
        ],
        1 => [
            'key' => 'etablissements',
            'label' => 'Établissements',
            'title' => 'Nombre d’établissements par niveau et régime',
            'kind' => 'simple_matrix',
            'columns' => [
                'pre_primaire' => 'Pré-primaire',
                'primaire' => 'Primaire',
                'secondaire' => 'Secondaire',
            ],
        ],
        2 => [
            'key' => 'preprim_classes',
            'label' => 'Pré-prim. classes',
            'title' => 'Pré-primaire — Classes organisées',
            'kind' => 'simple_matrix',
            'section' => 'ENSEIGNEMENT PRÉ-PRIMAIRE',
            'columns' => [
                'annee_1' => '1ère année',
                'annee_2' => '2è année',
                'annee_3' => '3è année',
            ],
        ],
        3 => [
            'key' => 'preprim_eleves',
            'label' => 'Pré-prim. élèves',
            'title' => 'Pré-primaire — Enfants inscrits (G/F)',
            'kind' => 'gender_matrix',
            'section' => 'ENSEIGNEMENT PRÉ-PRIMAIRE',
            'columns' => [
                'annee_1' => '1ère année',
                'annee_2' => '2è année',
                'annee_3' => '3è année',
            ],
        ],
        4 => [
            'key' => 'preprim_educateurs',
            'label' => 'Pré-prim. éducateurs',
            'title' => 'Pré-primaire — Éducateurs (qualif. × sexe)',
            'kind' => 'gender_matrix',
            'section' => 'ENSEIGNEMENT PRÉ-PRIMAIRE',
            'sex_keys' => ['H', 'F'],
            'columns' => [
                'EAP_D3' => 'EAP, D3',
                'D4' => 'D4',
                'EM' => 'EM',
                'D6' => 'D6',
                'AUTRE' => 'Autre',
            ],
        ],
        5 => [
            'key' => 'prim_classes',
            'label' => 'Prim. classes',
            'title' => 'Primaire — Classes organisées',
            'kind' => 'simple_matrix',
            'section' => 'ENSEIGNEMENT PRIMAIRE',
            'columns' => [
                'annee_1' => '1ère année',
                'annee_2' => '2e année',
                'annee_3' => '3e année',
                'annee_4' => '4e année',
                'annee_5' => '5e année',
                'annee_6' => '6e année',
            ],
        ],
        6 => [
            'key' => 'prim_eleves',
            'label' => 'Prim. élèves',
            'title' => 'Primaire — Élèves inscrits (G/F)',
            'kind' => 'gender_matrix',
            'section' => 'ENSEIGNEMENT PRIMAIRE',
            'columns' => [
                'annee_1' => '1ère année',
                'annee_2' => '2e année',
                'annee_3' => '3e année',
                'annee_4' => '4e année',
                'annee_5' => '5e année',
                'annee_6' => '6e année',
            ],
        ],
        7 => [
            'key' => 'prim_enseignants',
            'label' => 'Prim. enseignants',
            'title' => 'Primaire — Personnel enseignant (qualif. × sexe)',
            'kind' => 'gender_matrix',
            'section' => 'ENSEIGNEMENT PRIMAIRE',
            'sex_keys' => ['H', 'F'],
            'columns' => [
                'EAP_D3' => 'EAP, D3',
                'D4' => 'D4',
                'D6' => 'D6',
                'AUTRE' => 'Autre',
            ],
        ],
        8 => [
            'key' => 'sec_classes',
            'label' => 'Sec. classes',
            'title' => 'Secondaire — Classes organisées',
            'kind' => 'simple_matrix',
            'section' => 'ENSEIGNEMENT SECONDAIRE',
            'columns' => [
                'annee_7' => '7e année',
                'annee_8' => '8e année',
                'annee_1' => '1ère année',
                'annee_2' => '2e année',
                'annee_3' => '3e année',
                'annee_4' => '4e année',
            ],
        ],
        9 => [
            'key' => 'sec_eleves',
            'label' => 'Sec. élèves',
            'title' => 'Secondaire — Élèves inscrits (G/F)',
            'kind' => 'gender_matrix',
            'section' => 'ENSEIGNEMENT SECONDAIRE',
            'columns' => [
                'annee_7' => '7e année',
                'annee_8' => '8e année',
                'annee_1' => '1ère année',
                'annee_2' => '2e année',
                'annee_3' => '3e année',
                'annee_4' => '4e année',
            ],
        ],
        10 => [
            'key' => 'sec_type',
            'label' => 'Sec. types',
            'title' => 'Secondaire — Élèves par type d’enseignement (simplifié)',
            'kind' => 'type_matrix',
            'section' => 'ENSEIGNEMENT SECONDAIRE',
            'columns' => [
                'annee_7' => '7e / 1ère',
                'annee_8' => '8e / 2ème',
                'annee_1' => '1ère Hum.',
                'annee_2' => '2ème Hum.',
                'annee_3' => '3ème Hum.',
                'annee_4' => '4ème Hum.',
            ],
        ],
        11 => [
            'key' => 'sec_personnel',
            'label' => 'Sec. personnel',
            'title' => 'Secondaire — Personnel enseignant (qualif. × sexe)',
            'kind' => 'gender_matrix',
            'section' => 'ENSEIGNEMENT SECONDAIRE',
            'sex_keys' => ['H', 'F'],
            'columns' => [
                'EAP_D3' => 'EAP, D3',
                'D4' => 'D4',
                'Licence' => 'Licence',
                'Master' => 'Master',
                'AUTRE' => 'Autre',
            ],
        ],
        12 => [
            'key' => 'recap',
            'label' => 'Récap',
            'title' => 'Récapitulatif et soumission',
        ],
    ],
];
